apiVersion: v1
kind: Service
metadata:
  name: analytics-dashboard
  labels:
    app: analytics-dashboard
spec:
  type: ClusterIP
  selector:
    app: analytics-dashboard
  ports:
    - port: 8050
      targetPort: 8050
      protocol: TCP
      name: http
